version: '3'
services:
  flask-main:
    image: flask-main:latest
    ports:
      - "8000:8000"
  flask-auth:
    image: flask-auth:latest
    ports:
      - "8001:8001"
  flask-booking:
    image: flask-booking:latest
    ports:
      - "8002:8002"